package com.example.demo.entity;

public class article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_title
     *
     * @mbggenerated
     */
    private String articleTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_content
     *
     * @mbggenerated
     */
    private String articleContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.master_id
     *
     * @mbggenerated
     */
    private Integer masterId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_title
     *
     * @return the value of article.article_title
     *
     * @mbggenerated
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_title
     *
     * @param articleTitle the value for article.article_title
     *
     * @mbggenerated
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle == null ? null : articleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_content
     *
     * @return the value of article.article_content
     *
     * @mbggenerated
     */
    public String getArticleContent() {
        return articleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_content
     *
     * @param articleContent the value for article.article_content
     *
     * @mbggenerated
     */
    public void setArticleContent(String articleContent) {
        this.articleContent = articleContent == null ? null : articleContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.master_id
     *
     * @return the value of article.master_id
     *
     * @mbggenerated
     */
    public Integer getMasterId() {
        return masterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.master_id
     *
     * @param masterId the value for article.master_id
     *
     * @mbggenerated
     */
    public void setMasterId(Integer masterId) {
        this.masterId = masterId;
    }
}