package com.example.demo.entity;

public class emailGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.GROUP_ID
     *
     * @mbggenerated
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.GROUP_NAME
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_group.COPY_EMAIL_RECIPIENT
     *
     * @mbggenerated
     */
    private String copyEmailRecipient;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.GROUP_ID
     *
     * @return the value of tb_group.GROUP_ID
     *
     * @mbggenerated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.GROUP_ID
     *
     * @param groupId the value for tb_group.GROUP_ID
     *
     * @mbggenerated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.GROUP_NAME
     *
     * @return the value of tb_group.GROUP_NAME
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.GROUP_NAME
     *
     * @param groupName the value for tb_group.GROUP_NAME
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_group.COPY_EMAIL_RECIPIENT
     *
     * @return the value of tb_group.COPY_EMAIL_RECIPIENT
     *
     * @mbggenerated
     */
    public String getCopyEmailRecipient() {
        return copyEmailRecipient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_group.COPY_EMAIL_RECIPIENT
     *
     * @param copyEmailRecipient the value for tb_group.COPY_EMAIL_RECIPIENT
     *
     * @mbggenerated
     */
    public void setCopyEmailRecipient(String copyEmailRecipient) {
        this.copyEmailRecipient = copyEmailRecipient == null ? null : copyEmailRecipient.trim();
    }
}