package com.example.demo.entity;

public class emailTemplateWithBLOBs extends emailTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_email_template.MAIN_EMAIL_RECIPIENT
     *
     * @mbggenerated
     */
    private String mainEmailRecipient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_email_template.EMAIL_TEMPLATE_NAME
     *
     * @mbggenerated
     */
    private String emailTemplateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_email_template.EMAIL_TITLE
     *
     * @mbggenerated
     */
    private String emailTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_email_template.RELEASE_RANGE
     *
     * @mbggenerated
     */
    private String releaseRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_email_template.PRE_CONDITION
     *
     * @mbggenerated
     */
    private String preCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_email_template.CONFIGURATION_CHANGES
     *
     * @mbggenerated
     */
    private String configurationChanges;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_email_template.RELEASE_ORDER
     *
     * @mbggenerated
     */
    private String releaseOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_email_template.RELEASE_BRANCH
     *
     * @mbggenerated
     */
    private String releaseBranch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_email_template.RELEASE_FUNCTION
     *
     * @mbggenerated
     */
    private String releaseFunction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_email_template.POST_CONDITION
     *
     * @mbggenerated
     */
    private String postCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_email_template.ROLLBACK_PLAN
     *
     * @mbggenerated
     */
    private String rollbackPlan;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_email_template.MAIN_EMAIL_RECIPIENT
     *
     * @return the value of tb_email_template.MAIN_EMAIL_RECIPIENT
     *
     * @mbggenerated
     */
    public String getMainEmailRecipient() {
        return mainEmailRecipient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_email_template.MAIN_EMAIL_RECIPIENT
     *
     * @param mainEmailRecipient the value for tb_email_template.MAIN_EMAIL_RECIPIENT
     *
     * @mbggenerated
     */
    public void setMainEmailRecipient(String mainEmailRecipient) {
        this.mainEmailRecipient = mainEmailRecipient == null ? null : mainEmailRecipient.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_email_template.EMAIL_TEMPLATE_NAME
     *
     * @return the value of tb_email_template.EMAIL_TEMPLATE_NAME
     *
     * @mbggenerated
     */
    public String getEmailTemplateName() {
        return emailTemplateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_email_template.EMAIL_TEMPLATE_NAME
     *
     * @param emailTemplateName the value for tb_email_template.EMAIL_TEMPLATE_NAME
     *
     * @mbggenerated
     */
    public void setEmailTemplateName(String emailTemplateName) {
        this.emailTemplateName = emailTemplateName == null ? null : emailTemplateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_email_template.EMAIL_TITLE
     *
     * @return the value of tb_email_template.EMAIL_TITLE
     *
     * @mbggenerated
     */
    public String getEmailTitle() {
        return emailTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_email_template.EMAIL_TITLE
     *
     * @param emailTitle the value for tb_email_template.EMAIL_TITLE
     *
     * @mbggenerated
     */
    public void setEmailTitle(String emailTitle) {
        this.emailTitle = emailTitle == null ? null : emailTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_email_template.RELEASE_RANGE
     *
     * @return the value of tb_email_template.RELEASE_RANGE
     *
     * @mbggenerated
     */
    public String getReleaseRange() {
        return releaseRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_email_template.RELEASE_RANGE
     *
     * @param releaseRange the value for tb_email_template.RELEASE_RANGE
     *
     * @mbggenerated
     */
    public void setReleaseRange(String releaseRange) {
        this.releaseRange = releaseRange == null ? null : releaseRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_email_template.PRE_CONDITION
     *
     * @return the value of tb_email_template.PRE_CONDITION
     *
     * @mbggenerated
     */
    public String getPreCondition() {
        return preCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_email_template.PRE_CONDITION
     *
     * @param preCondition the value for tb_email_template.PRE_CONDITION
     *
     * @mbggenerated
     */
    public void setPreCondition(String preCondition) {
        this.preCondition = preCondition == null ? null : preCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_email_template.CONFIGURATION_CHANGES
     *
     * @return the value of tb_email_template.CONFIGURATION_CHANGES
     *
     * @mbggenerated
     */
    public String getConfigurationChanges() {
        return configurationChanges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_email_template.CONFIGURATION_CHANGES
     *
     * @param configurationChanges the value for tb_email_template.CONFIGURATION_CHANGES
     *
     * @mbggenerated
     */
    public void setConfigurationChanges(String configurationChanges) {
        this.configurationChanges = configurationChanges == null ? null : configurationChanges.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_email_template.RELEASE_ORDER
     *
     * @return the value of tb_email_template.RELEASE_ORDER
     *
     * @mbggenerated
     */
    public String getReleaseOrder() {
        return releaseOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_email_template.RELEASE_ORDER
     *
     * @param releaseOrder the value for tb_email_template.RELEASE_ORDER
     *
     * @mbggenerated
     */
    public void setReleaseOrder(String releaseOrder) {
        this.releaseOrder = releaseOrder == null ? null : releaseOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_email_template.RELEASE_BRANCH
     *
     * @return the value of tb_email_template.RELEASE_BRANCH
     *
     * @mbggenerated
     */
    public String getReleaseBranch() {
        return releaseBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_email_template.RELEASE_BRANCH
     *
     * @param releaseBranch the value for tb_email_template.RELEASE_BRANCH
     *
     * @mbggenerated
     */
    public void setReleaseBranch(String releaseBranch) {
        this.releaseBranch = releaseBranch == null ? null : releaseBranch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_email_template.RELEASE_FUNCTION
     *
     * @return the value of tb_email_template.RELEASE_FUNCTION
     *
     * @mbggenerated
     */
    public String getReleaseFunction() {
        return releaseFunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_email_template.RELEASE_FUNCTION
     *
     * @param releaseFunction the value for tb_email_template.RELEASE_FUNCTION
     *
     * @mbggenerated
     */
    public void setReleaseFunction(String releaseFunction) {
        this.releaseFunction = releaseFunction == null ? null : releaseFunction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_email_template.POST_CONDITION
     *
     * @return the value of tb_email_template.POST_CONDITION
     *
     * @mbggenerated
     */
    public String getPostCondition() {
        return postCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_email_template.POST_CONDITION
     *
     * @param postCondition the value for tb_email_template.POST_CONDITION
     *
     * @mbggenerated
     */
    public void setPostCondition(String postCondition) {
        this.postCondition = postCondition == null ? null : postCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_email_template.ROLLBACK_PLAN
     *
     * @return the value of tb_email_template.ROLLBACK_PLAN
     *
     * @mbggenerated
     */
    public String getRollbackPlan() {
        return rollbackPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_email_template.ROLLBACK_PLAN
     *
     * @param rollbackPlan the value for tb_email_template.ROLLBACK_PLAN
     *
     * @mbggenerated
     */
    public void setRollbackPlan(String rollbackPlan) {
        this.rollbackPlan = rollbackPlan == null ? null : rollbackPlan.trim();
    }
}