package com.example.demo.entity;

import java.util.Date;

public class email {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_email.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_email.EMAIL_TEMPLATE_ID
     *
     * @mbggenerated
     */
    private Integer emailTemplateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_email.GROUP_ID
     *
     * @mbggenerated
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_email.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_email.SEND_TIME
     *
     * @mbggenerated
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_email.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_email.EMAIL_CONTENT
     *
     * @mbggenerated
     */
    private String emailContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_email.ID
     *
     * @return the value of tb_email.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_email.ID
     *
     * @param id the value for tb_email.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_email.EMAIL_TEMPLATE_ID
     *
     * @return the value of tb_email.EMAIL_TEMPLATE_ID
     *
     * @mbggenerated
     */
    public Integer getEmailTemplateId() {
        return emailTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_email.EMAIL_TEMPLATE_ID
     *
     * @param emailTemplateId the value for tb_email.EMAIL_TEMPLATE_ID
     *
     * @mbggenerated
     */
    public void setEmailTemplateId(Integer emailTemplateId) {
        this.emailTemplateId = emailTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_email.GROUP_ID
     *
     * @return the value of tb_email.GROUP_ID
     *
     * @mbggenerated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_email.GROUP_ID
     *
     * @param groupId the value for tb_email.GROUP_ID
     *
     * @mbggenerated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_email.CREATE_TIME
     *
     * @return the value of tb_email.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_email.CREATE_TIME
     *
     * @param createTime the value for tb_email.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_email.SEND_TIME
     *
     * @return the value of tb_email.SEND_TIME
     *
     * @mbggenerated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_email.SEND_TIME
     *
     * @param sendTime the value for tb_email.SEND_TIME
     *
     * @mbggenerated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_email.STATUS
     *
     * @return the value of tb_email.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_email.STATUS
     *
     * @param status the value for tb_email.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_email.EMAIL_CONTENT
     *
     * @return the value of tb_email.EMAIL_CONTENT
     *
     * @mbggenerated
     */
    public String getEmailContent() {
        return emailContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_email.EMAIL_CONTENT
     *
     * @param emailContent the value for tb_email.EMAIL_CONTENT
     *
     * @mbggenerated
     */
    public void setEmailContent(String emailContent) {
        this.emailContent = emailContent == null ? null : emailContent.trim();
    }
}