package com.example.demo.entity;

public class master {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master.master_name
     *
     * @mbggenerated
     */
    private String masterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master.master_password
     *
     * @mbggenerated
     */
    private String masterPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master.id
     *
     * @return the value of master.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master.id
     *
     * @param id the value for master.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master.master_name
     *
     * @return the value of master.master_name
     *
     * @mbggenerated
     */
    public String getMasterName() {
        return masterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master.master_name
     *
     * @param masterName the value for master.master_name
     *
     * @mbggenerated
     */
    public void setMasterName(String masterName) {
        this.masterName = masterName == null ? null : masterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master.master_password
     *
     * @return the value of master.master_password
     *
     * @mbggenerated
     */
    public String getMasterPassword() {
        return masterPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master.master_password
     *
     * @param masterPassword the value for master.master_password
     *
     * @mbggenerated
     */
    public void setMasterPassword(String masterPassword) {
        this.masterPassword = masterPassword == null ? null : masterPassword.trim();
    }
}