package com.example.demo.mapper;

import com.example.demo.entity.emailTemplate;
import com.example.demo.entity.emailTemplateWithBLOBs;

public interface emailTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_email_template
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer emailTemplateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_email_template
     *
     * @mbggenerated
     */
    int insert(emailTemplateWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_email_template
     *
     * @mbggenerated
     */
    int insertSelective(emailTemplateWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_email_template
     *
     * @mbggenerated
     */
    emailTemplateWithBLOBs selectByPrimaryKey(Integer emailTemplateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_email_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(emailTemplateWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_email_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(emailTemplateWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_email_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(emailTemplate record);

    emailTemplate  selectByTemplateName(String templateName);
}