package com.example.demo.mapper;

import com.example.demo.entity.email;
import com.example.demo.entity.emailGroup;

import java.util.List;

public interface emailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_email
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_email
     *
     * @mbggenerated
     */
    int insert(email record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_email
     *
     * @mbggenerated
     */
    int insertSelective(email record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_email
     *
     * @mbggenerated
     */
    email selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_email
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(email record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_email
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(email record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_email
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(email record);

    List<email> selectByTemplateIdAndGroupId(int groupId,int templateId);
}