package com.example.demo.mapper;

import com.example.demo.entity.emailGroup;

public interface emailGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group
     *
     * @mbggenerated
     */
    int insert(emailGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group
     *
     * @mbggenerated
     */
    int insertSelective(emailGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group
     *
     * @mbggenerated
     */
    emailGroup selectByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(emailGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(emailGroup record);

    emailGroup selectByGroupName(String groupName);
}