package com.example.demo.mapper;

import com.example.demo.entity.master;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

@Mapper
public interface masterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master
     *
     * @mbggenerated
     */
    int insert(master record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master
     *
     * @mbggenerated
     */
    int insertSelective(master record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master
     *
     * @mbggenerated
     */
    master selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(master record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(master record);

    /**注册，插入master数据**/
    //int addMaster(@Param("username") String username, @Param("password") String password);
    int addMaster(master master);

    /**登陆，查询master数据**/
    master masterLogin(master master);

    List<Map<String, Object>> queryAllMaster();

}